version: '{build}'

skip_tags: true

environment:
  matrix:
    - ruby_version: "23"
    - ruby_version: "23-x64"

install:
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - gem install bundler --no-document -v 1.13.5
  - SET BUNDLE_GEMFILE=Gemfile.norbnacl
  - bundle _1.13.5_ install --retry=3
  - cinst freesshd
  - cinst putty

test_script:
  - SET BUNDLE_GEMFILE=Gemfile.norbnacl
  - bundle _1.13.5_ exec rake test
  - bundle _1.13.5_ exec ruby test\manual\test_pageant.rb

build: off
